forcedotcom/lightning-language-server

packages/lightning-lsp-common/src/__tests__/context.test.ts
packages/lightning-lsp-common/src/context.ts
packages/lightning-lsp-common/src/resources/sfdx/eslintrc-sfdx.json
packages/lwc-language-server/src/__tests__/config.test.ts
packages/lwc-language-server/src/html-language-service/__tests__/htmlCompletion.test.ts
packages/lwc-language-server/src/html-language-service/__tests__/htmlDefinition.test.ts
packages/lwc-language-server/src/html-language-service/__tests__/htmlOver.test.ts
packages/lwc-language-server/src/metadata-utils/__tests__/custom-components-util.test.ts

Language server will no longer write out an eslintrc file to the users workspace
[#1644](https://github.com/forcedotcom/salesforcedx-vscode/issues/1644)

don't write eslintrc file

---

packages/lwc-language-server/src/__tests__/config.test.ts
packages/lwc-language-server/src/config.ts
packages/lwc-language-server/src/metadata-utils/custom-components-util.ts
packages/lwc-language-server/src/server.ts

* Added onDidSave event handler to LWC server connection.
* Modified writeConfigs to reduce config update attempts.
* Added a check for differences prior to writing to config file.
W-6860946

[W-6860946] Reduce writes to jsconfig.json

---

package.json
yarn.lock

Set resolutions for security alerts.
Nested packages still depend on vulnerable versions.
https://github.com/forcedotcom/lightning-language-server/network/alerts

[W-7120063] Fix Security Alerts

---

.circleci/config.yml
.gitignore
README.md
codecov.yml

Adds CodeCov.io to the repository
@W-7120214@

Publish code coverage data to CodeCov.io

---

packages/lwc-language-server/src/config.ts

Added a check to verify if the jsconfig content needs to be updated.
@W-7151419@

[W-7151419] Don't update jsconfig with existing content

---

package.json

Force publish for all the lsp packages on checkins to master
@W-6819905@

Force publish for lerna version on deploy

---

CONTRIBUTING.md
packages/aura-language-server/src/resources/lwc-standard.json
packages/lwc-language-server/src/metadata-utils/custom-components-util.ts
packages/lwc-language-server/src/resources/lwc-standard.json

Updates the lwc-standard.json files to the latest for 224
@W-7158536@

Lwc standard

---

packages/lwc-language-server/src/metadata-utils/content-assets-util.ts

Introduce save and load content assets from file

---

packages/lwc-language-server/src/metadata-utils/custom-labels-util.ts

Introduce save and load custom labels from file

---

packages/lwc-language-server/src/metadata-utils/static-resources-util.ts

Introduce save and load static resources from file

---

packages/lightning-lsp-common/src/indexer/tagInfo.ts
packages/lwc-language-server/src/metadata-utils/custom-components-util.ts

Introduce save and load custom components from file

---

packages/lwc-language-server/src/indexer.ts

This method should be called from `server.ts` on shutdown 

Introduce persisting all indexes from indexer

---

.circleci/config.yml

Updates the CircleCI configuration to release from main branch and includes other configuration changes.
@W-7785612@

Update circleci configuration. Part 1

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Update lds.d.ts for 226
@W-7821566@

Update lds.d.ts for 226

---

.circleci/config.yml
package.json

Update publish flow so it doesn't commit when a release fails.
@W-7785612@

Update publish circleci flow

---

.circleci/config.yml

Porting CircleCI changes from PR #182

Move to .npmrc for circleci config (#182)

---

packages/lwc-language-server/src/__tests__/tag.test.ts
packages/lwc-language-server/src/component-indexer.ts
packages/lwc-language-server/src/lwc-server.ts
packages/lwc-language-server/src/tag.ts
packages/lwc-language-server/src/typing.ts

This PR fixes the following issues:
- Receiving events without data to process
- Persisting custom component information when the file path does not exist
- Persisting custom component information after indexing a project
- Not showing correct custom component information when triggering onCompletion for javascript lwc files
@W-7971496@

LWC bug fixes

---

.circleci/config.yml
package.json

Update publish configurations
Add volta configuration to project
The publish configuration is currently different than the rest of our repos. We'll move to the new configuration in future PRs
@W-7785612@

Update publish configuration. Add volta configurations

---

.gitignore
.npmrc
lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package.json

Porting last release commits to develop branch
@W-7785612@

Backport 3.0.2 commits

---

.circleci/config.yml
SECURITY.md
package.json
packages/lwc-language-server/src/__tests__/tag.test.ts
packages/lwc-language-server/src/component-indexer.ts
packages/lwc-language-server/src/lwc-server.ts
packages/lwc-language-server/src/tag.ts

Port the latest changes for release 3.0.3

Port release 3.0.3

---

lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package.json

Updated version 3.0.4

---

packages/lightning-lsp-common/package.json
packages/lightning-lsp-common/scripts/copy_typings.js
packages/lightning-lsp-common/src/decorators/index.ts
packages/lightning-lsp-common/src/indexer/tagInfo.ts
packages/lwc-language-server/package.json
packages/lwc-language-server/src/decorators/index.ts
packages/lwc-language-server/src/javascript/__tests__/compiler.test.ts
packages/lwc-language-server/src/javascript/compiler.ts
packages/lwc-language-server/src/lwc-server.ts
packages/lwc-language-server/src/tag.ts
yarn.lock

This PR updates the @lwc dependencies inside the packages
To finish updating the @lwc dependencies, just rest to update the @lwc/compiler, but to update this dependency, some refactor is required, so this change will be into different PRs
W-7976730

Update @lwc dependencies

---

packages/aura-language-server/package.json
packages/aura-language-server/scripts/build.js
packages/lightning-lsp-common/copy-static-assets.ts
packages/lightning-lsp-common/package.json
packages/lightning-lsp-common/scripts/build.js
packages/lightning-lsp-common/scripts/copy_typings.js
packages/lightning-lsp-common/src/decorators/index.ts
packages/lightning-lsp-common/src/indexer/tagInfo.ts
packages/lwc-language-server/package.json
packages/lwc-language-server/scripts/build.js
packages/lwc-language-server/src/decorators/index.ts
packages/lwc-language-server/src/javascript/__tests__/compiler.test.ts
packages/lwc-language-server/src/javascript/compiler.ts
packages/lwc-language-server/src/lwc-server.ts
packages/lwc-language-server/src/tag.ts
yarn.lock

Ports commits for release of v3.0.7

Port Commits for Release v3.0.7

---

lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package-lock.json
packages/lwc-language-server/package.json

Porting version bump from main

Updated version 3.0.7

---

packages/aura-language-server/package.json
packages/aura-language-server/src/aura-indexer/__tests__/indexer.spec.ts
packages/aura-language-server/src/aura-indexer/indexer.ts

This PR is a research of why we having failures with the snapshot comparing  in a test inside aura-indexer. 
This is a inconsitent problem, so this PR will have commits to try trigger the problem, as we  don't really know what is triggering this.
W-8101555

CircleCi failing with snapshot compare

---

.vscode/settings.json
package.json
packages/aura-language-server/package.json
packages/aura-language-server/src/aura-indexer/__tests__/indexer.spec.ts
packages/aura-language-server/src/aura-indexer/indexer.ts
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package.json
packages/lwc-language-server/src/__tests__/lwc-server.test.ts
packages/lwc-language-server/src/typing-indexer.ts

Porting changes for release 3.0.8

Port 3.0.8

---

packages/aura-language-server/src/tern-server/__tests__/string-util.test.ts
packages/lightning-lsp-common/src/html-language-service/utils/__tests__/strings.test.ts

Port of PR #248  with a few updates to it. Slightly improves the test coverage of this repo by testing the string helper classes.
#247, @W-8155310@

Test string util classes

---

lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package-lock.json
packages/lwc-language-server/package.json

Porting version bump for release 3.0.8

Updated version 3.0.8

---

.vscode/tasks.json
package.json
scripts/port-changes.js

Same scripts and configuration as the port changes in the other repos.
@W-8156980

chore: automation for porting commits from develop to main (@W-8156980)

---

.vscode/tasks.json
package.json
packages/aura-language-server/src/server.ts
packages/aura-language-server/src/tern-server/__tests__/string-util.test.ts
packages/lightning-lsp-common/src/html-language-service/utils/__tests__/strings.test.ts
packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts
packages/lwc-language-server/src/__tests__/lwc-server.test.ts
packages/lwc-language-server/src/lwc-server.ts
scripts/port-changes.js

Port pr v3.0.9

---

.vscode/tasks.json
scripts/port-changes.js

Updates the port-changes logic to match the recent changes made to the Source Deploy Retrieve Library.
@W-8156980@

chore: update port-changes logic (@W-8156980)

---

lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package-lock.json
packages/lwc-language-server/package.json

Port version bump 3.0.9

---

.commitlintrc.json
.vscode/tasks.json
CONTRIBUTING.md
README.md
package.json
yarn.lock

Implements commitizen for commit format enforcement.
@W-8165492@

chore: implement commitizen (@W-8165492)

---

.circleci/config.yml
.commitlintrc.json
.vscode/tasks.json
CONTRIBUTING.md
README.md
package.json
packages/lwc-language-server/src/__tests__/typing-indexer.test.ts
packages/lwc-language-server/src/__tests__/typing.test.ts
packages/lwc-language-server/src/typing-indexer.ts
packages/lwc-language-server/src/typing.ts
scripts/port-changes.js
yarn.lock

Porting changes to main for v3.0.10

chore: Port PR v3.0.10

---

lerna.json
packages/aura-language-server/package.json
packages/lightning-lsp-common/package.json
packages/lwc-language-server/package-lock.json
packages/lwc-language-server/package.json

Porting version bump from main to develop

Updated version 3.0.10

---

packages/aura-language-server/src/server.ts
packages/lwc-language-server/src/__tests__/lwc-server.test.ts
packages/lwc-language-server/src/lwc-server.ts

Disable triggering completions for curly braces. A follow up PR will address completions for imports and attributes which uses this character.
@W-8289975@

fix: disable curly braces from triggering completions

---

packages/aura-language-server/src/server.ts
packages/lwc-language-server/src/__tests__/lwc-server.test.ts
packages/lwc-language-server/src/lwc-server.ts

Porting changes for release 3.0.11

fix: disable curly braces from triggering completions (#278)

---

README.md
packages/aura-language-server/CONTRIBUTING.md
packages/lwc-language-server/CONTRIBUTING.md

Removes some outdated documentation and replaces it with a reference to the correct debugging setup to use. Also adds a different way of launching the multiroot workspace.
@W-8515754@

docs: update lightning lsp documentation for debugging

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Adds typings for lightning/analyticsWaveApi lds methods.
@W-8973196@
cc: @mblumreich, @ychhetri, @lindsey-burnett, @danny6514, @yijian-wang, @reidaelliott, @karihotchkiss

feat(common): add analyticsWaveApi types

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Add doc links to the jsdoc for the `analyticsWaveApi` methods now that they're public.
@W-9556613@
cc: @mblumreich, @ychhetri, @reidaelliott, @karihotchkiss, @jolley-sfdc

feat(common): add doc urls to analyticsWaveApi method jsdocs

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Port PR Release v3.0.14

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Original PR - https://github.com/forcedotcom/lightning-language-server/pull/421

Add typings for getMetrics Scale Center LDS adapter

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

What does this PR do?
- Adds typings for lightning/analyticsWaveApi lds methods.
What issues does this PR fix or reference?
@W-9717230@, #447, PDT WI: @W-9882715@

feat: add 234 analyticsWaveApi types

---

CONTRIBUTING.md
README.md

Updates some of the occurrences of "master" to "main'

fix: renamed master to main

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Adds method signatures and documentation for:
getRelatedListInfoBatch
getRelatedListRecordsBatch
@W-10302274@

feat(common): add typings for rl batch wires

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Add wire adapter type for getDataflow in lightning/analyticsWaveApi package.
@W-10238088@

feat: Add type for getDataflow wire adapter

---

packages/lightning-lsp-common/src/__tests__/utils.test.ts
packages/lightning-lsp-common/src/utils.ts
packages/lwc-language-server/src/__tests__/lwc-data-provider.test.ts
packages/lwc-language-server/src/__tests__/lwc-server.test.ts
packages/lwc-language-server/src/lwc-data-provider.ts
packages/lwc-language-server/src/lwc-server.ts

- Provide controller options for code autocompletion for LWC bind variables(finished by Roy).
- Add unit tests(finished by Flora).
@W-10536511@

feat: enhance autocompletion across JS/HTML

---

.git2gus/config.json

Updates git2gus config with more accurate information.

chore: update git2gus config

---

.circleci/config.yml

Updates our CI context to include the NPM token.

fix: update CI

---

.github/workflows/onPushToMain.yml
.github/workflows/onRelease.yml

- updates secrets
@W-11596519@

chore: secrets update

---

.github/workflows/onRelease.yml

Alter the flow for an NPM release to be after a GH release has been created.
#521 continued @W-11955917@

ci: simplify onRelease GHA

---

.github/workflows/testCommitExceptMain.yml

Allows for manual invocation of tests from Actions tab.
Hopefully allow us to manually run tests for #528.

chore: allow for manual test runs

---

packages/lightning-lsp-common/package.json
packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts
packages/lwc-language-server/package.json
packages/lwc-language-server/src/javascript/compiler.ts
test-workspaces/standard-workspace/package.json
yarn.lock

- New adapter for lightning/placeQuoteApi
- Add adapters from lightning/industriesSchedulerApi
- Add wire adapter type for getProgramTemplate in lightning/salesEnablementProgramApi 
- Upgrades LWC libraries (other than Compiler) to latest
@W-12350138@ - Closes #542 
@W-12401411@ - Closes #541 
@W-12333642@ - Closes #540 
@W-12246411@ - Closes #539, closes #538

feat: lightning adapter updates and update lwc versions

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

- Adds typings for new automated actions LDS adapter for applyReminder
@W-12491063@

feat: add typings for applyReminder

---

.git2gus/config.json

Adding the tag "community-contributor" creates a WI in our internal bug tracker. 
@W-13013847@ . Fixes forcedotcom/easywriter#155. Closes #562.

ci: Update community-contributor label to open Work

---

packages/lwc-language-server/src/component-indexer.ts

Performance enhancement to speed up initialization, particularly when working with large code bases. Tested locally, this has reduced the startup time for the extension from > 2 hours to around 2 minutes.
https://github.com/forcedotcom/salesforcedx-vscode/issues/4829

perf: improve time taken to init

---

packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts

Add wire adapter type for RUD adapters in lightning/salesEngagementWorkspaceApi
@W-13460311@
Closes https://github.com/forcedotcom/lightning-language-server/pull/572

feat: Add wire adapter type for RUD adapters in lightning/salesEngagementWorkspaceApi

---

.github/CODEOWNERS

https://salesforce-internal.slack.com/archives/C05DKNXJC15/p1690486398092009
#582

CODEOWNERS Asterisk Fix

---

.github/dependabot.yml
.github/workflows/automerge.yml

- Adds config for dependabot and automerge
@W-16407809@

chore: add dependabot and automerge strategy

---

package.json

@W-18704757 chore: rename top-level pkg
