- packages/lightning-lsp-common/src/resources/sfdx/typings/messageservice.d.ts
- packages/lwc-language-server/src/metadata-utils/__tests__/message-channel-util.test.ts
We don't want to add `createMessageChannel` to public docs right now as it's opening up usage of it when it really doesn't provide the pattern we want people to use. If they use `createMessageContext`,
1. the developer ergonomics aren't as great because now the developer has to explicitly export and pass around a reference to that channel
2. there's no namespace guarding or deploy time access checks
We can come up with the right story for when and how to talk about this API at a later time. For now it's mostly used internally and for some testing off core.
> LMS Remove createMessageChannel from the Intellisense

- packages/lightning-lsp-common/src/__tests__/workspace-type.test.ts
- packages/lightning-lsp-common/src/shared.ts
We're now checking the following cases to determine if a workspace
should be STANDARD_LWC:
- A `lwc.config.js` file exists at the root
- The `package.json` at the root has one of the following keys in
`dependencies` or `devDepencencies`
- starts with `@lwc/`
- `lwc-services`
- The `package.json` has a root key (configuration) of `lwc`
> activate on the lwc-services dependency

- packages/lightning-lsp-common/src/__tests__/workspace-type.test.ts
- packages/lightning-lsp-common/src/shared.ts
According to the [LWC Docs](https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution#lwc-configuration) we should using the `lwc.config.json` file to determine if the workspace is "STANDARD_LWC" not a `lwc.config.js` file.
> Rename use of 'lwc.config.js` to `lwc.config.json`

- packages/lwc-language-server/src/constants.ts
- packages/lwc-language-server/src/javascript/__tests__/compiler.test.ts
- packages/lwc-language-server/src/javascript/compiler.ts
Fixes error message in SLDS extensions output when working with an LWC file that contains compile errors.
The cause of the issue is that LWC language server generates a diagnostics message with an overflowing value, which get passed on by VS Code and SLDS extension could not handle it.
There's a similar [issue](https://github.com/microsoft/vscode/issues/80288) from VS Code where the diagnostics are generated from problem matchers.
Thanks @billyma for the help in locating the root cause.
Fixes https://github.com/forcedotcom/salesforcedx-vscode/issues/2074, https://github.com/forcedotcom/salesforcedx-vscode-slds/issues/25, @W-7387177@
> Fix "Request textDocument/codeAction failed" in SLDS extension

- .circleci/config.yml
Updates the circleci config to output the NPM_TOKEN into .npmrc. This matches what is done in the apex library.
> Move to .npmrc for circleci config

- packages/lwc-language-server/src/lwc-server.ts
- packages/lwc-language-server/src/tag.ts
The javascript completions need to be of type Folder and follow the component filename format
@W-7971496@
> Update js onCompletion to Folder and file name

- packages/lightning-lsp-common/package.json
- packages/lightning-lsp-common/src/__tests__/test-utils.ts
- packages/lightning-lsp-common/src/html-language-service/services/htmlCompletion.ts
- packages/lightning-lsp-common/src/html-language-service/services/htmlLinks.ts
- packages/lightning-lsp-common/src/utils.ts
- packages/lwc-language-server/package-lock.json
- packages/lwc-language-server/package.json
- packages/lwc-language-server/src/__tests__/component-indexer.test.ts
- packages/lwc-language-server/src/__tests__/lwc-server.test.ts
- packages/lwc-language-server/src/__tests__/test-utils.ts
- packages/lwc-language-server/src/javascript/compiler.ts
- packages/lwc-language-server/src/lwc-server.ts
- packages/lwc-language-server/src/tag.ts
- packages/lwc-language-server/test-workspaces
This PR updates the dependency vscode-uri, also it changes the code where it uses it, cause URI is no longer exported as default.
The Ticket corresponding to this changes is: W-7976730
> Bump of vscode-uri version

- packages/lightning-lsp-common/package.json
This PR adds the dependency @salesforce/apex into the lightning-lsp-common package. 
It's copied on scripts/copy_typings.js, and used on test lightning-lsp-common/src/_tests_/context.test.ts:201 (Where it checks for apex.d.ts file)
> Missed package @salesforce/apex

- .vscode/settings.json
- packages/lwc-language-server/src/__tests__/lwc-server.test.ts
- packages/lwc-language-server/src/typing-indexer.ts
Fix lwc server init in core modules: CORE_ALL and CORE_PARTIAL workspace.
The root cause of this issue is `typing-indexer` looks up `sfdxPackageDirsPattern` which is read from `sfdx-project.json`, but core workspaces don't have `sfdx-project.json` files.
@W-8108703@
> fix: fix lwc server init in core modules

- packages/aura-language-server/src/server.ts
- packages/lwc-language-server/src/__tests__/lwc-server.test.ts
- packages/lwc-language-server/src/lwc-server.ts
Update completion provider configs to trigger the event when a user types aura/lwc tag characters.
@W-8017548@, @W-8017525@
> Trigger completions on specific characters

- packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts
It adds typing for a new adapter getObjectInfos exposed through lightning/uiObjectInfoApi module. Porting #172 to develop.
@W-7454278@
> feat(common): add typings for getObjectInfos

- .circleci/config.yml
Restricts approval access for circle ci workflows. Only members of the GitHub Team 'PDT' should be able to approve workflows for publishing.
@W-8165486@
> chore: add context restriction for publish workflows

- packages/lwc-language-server/src/__tests__/typing-indexer.test.ts
- packages/lwc-language-server/src/__tests__/typing.test.ts
- packages/lwc-language-server/src/typing-indexer.ts
- packages/lwc-language-server/src/typing.ts
Fixes the issue of the language server throwing an error when parsing an empty custom labels file. 
https://github.com/forcedotcom/salesforcedx-vscode/issues/2575, @W-81658202
> fix: handle empty custom labels when creating types

- scripts/port-changes.js
1. Adds checks for error codes instead of strings. If an error code is not 0, we will exit with an error.
2. Changes the local branch update logic. Previously this was not accounting for fetches being performed on the current branch. By default this isn't allowed, which was causing an error. We can make use of the '-u' option, but per git man I don't believe we should use this flag. Instead, we will now just checkout main and do a pull to avoid this issue. It also ensures we always have the latest version as well.
-u flag Information:
> By default git fetch refuses to update the head which corresponds to the current branch. This flag disables the check. This is purely for the internal use for git pull to communicate with git fetch, and unless you are implementing your own Porcelain you …
> chore: update port logic to handle errors and updates for local branches

- packages/aura-language-server/src/aura-indexer/__tests__/indexer.spec.ts
Ignoring a test to isolate a failure in circleci
> chore: ignoring a test to isolate a failure in circleci

- .circleci/config.yml
Access common env variables across different projects from context defined at organizational settings.
> chore: use context for common env variables

- .vscode/launch.json
- packages/lwc-language-server/.vscode/launch.json
In conjunction with the vscode update, enables debugging again for the lwc language client.
@[W-10537405](https://gus.my.salesforce.com/a07EE00000l2RUFYA2)@
Unable to set break points and debug changes in the lighnting-language-server due to a port conflict with the soql language server.
Breakpoints working again!
> chore: updated lwc debug port

- packages/lwc-language-server/scripts/convert.js
- packages/lwc-language-server/src/__tests__/lwc-data-provider.test.ts
- packages/lwc-language-server/src/resources/standard-lwc.json
Added the iterator:it template directive to suggested attributes with others like for:each and
if:true. Fixed issue where description wasn't showing on any of the directives, and added links to
our docs as well. This also allow for flexible syntax, where the user wants to use another variable 
for 'it'.
@W-10536569@, @W-10542295@
The template directive iterator:it was not appearing in our list of auto-complete attributes, and description information was broken.
The directive appears, and the description information is now available for all other template directives. 🎉
> feat: add iterator syntax

- packages/lwc-language-server/src/__tests__/lwc-server.test.ts
- packages/lwc-language-server/src/lwc-server.ts
- Addresses a recent issue where we were providing autocomplete for curly braces in JS files, when we really only wanted to do so in HTML. This caused annoying and unhelpful autocomplete due to them firing off every time a conditional statement or method was declared. This reverts the JS autocomplete to how it was previously with a bit more semantic method naming to make it clear what the trigger characters are doing.
VS Code #3902. @W-10832653@
> fix: Prevent excessive autocompletion in template JS files

- package.json
If you run yarn install on a fresh clone of this repo, and you have Volta installed, you will get an error:
error jest-diff@27.4.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.4.0"
error Found incompatible module.
The reason is that the Volta node version is out of date. I bumped it, as well as the yarn version (just because we might as well).
> chore: update volta node/yarn versions

- packages/lightning-lsp-common/package.json
- packages/lightning-lsp-common/src/__tests__/workspace-type.test.ts
- packages/lwc-language-server/package.json
- packages/lwc-language-server/src/template/__tests__/linter.test.ts
- test-workspaces/standard-workspace/package.json
- yarn.lock
Updates LWC dependencies from 1.7.14 to 2.13.3.
Note the breaking change, which is that @lwc/engine was renamed to @lwc/engine-dom. I've fixed the references to @lwc/engine.
This fixes several issues, e.g. that certain warnings or errors that were added after 1.7.14 do not surface in the VS Code extension. Now, they do. For example, duplicate </template></template> tags (https://github.com/salesforce/lwc/pull/2649) now show a warning (yellow squiggle):
> chore: update lwc, engine, errors, and template-compiler

- packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts
Add wire adapter type for getProgramTemplates in lightning/salesEnablementProgramApi .
> @W-11223056 -  Add wire adapter type for getProgramTemplates in lightning/salesEnablementProgramApi package.

- packages/lwc-language-server/src/__tests__/tag.test.ts
- packages/lwc-language-server/src/javascript/__tests__/fixtures/navmetadata.js
- packages/lwc-language-server/src/tag.ts
Suppresses a noisy exception that occurs when trying to use the Hover or Go To Definition functionality on a component that we are not able to compile correctly due to the outdated LWC Compiler. One example of this error occurs when a component is using the NavigationMixin. This error is now logged quietly in the LWC output panel instead, so we can receive better reports from our users around the type of components that are not being handled correctly.
#493 
To test, open the ebikes-LWC repo, or another project using the NavigationMixin. For the ebikes repo, open the productListItem, hover over the {product.MSRP__C} (or any other attribute) and press Cmd to try and click through to the definition. The error `Request textDocument/definition failed. Message: Request textDocument/definition …
> fix: handle malformed tags quietly

- packages/lightning-lsp-common/src/logger.ts
- Gets rid of the double logging to the LWC Language Server Output Tab when Attribute Not Found
[@W-11307712@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000zN76PYAS/view)
- "Attribute x not found" was being logged twice per each cmd+click/hover when applicable
- "Attribute x not found" is being logged once per each cmd+click/hover when applicable
> fix: no more double logging to the LWC Lang Server Tab

- scripts/bump-lerna-version.js
Reviewing the failure of the release job in CI and started looking at docs for conventional-changelog-action.  Found we have some unmet requirements around the preCommit [here](https://github.com/TriPSs/conventional-changelog-action#pre-commit-hook).  It still may fail but get further due to us having the shelljs dependancy. 
#521 continued
> ci: update preCommit script to be a commonjs module

- .github/workflows/onPushToMain.yml
- .github/workflows/startManualRelease.yml
Swaps the order of checkout and node setup in 2 github actions so we can use the nvmrc of the checked out code to determine the node version used.
Follow-up fix to #549
> ci: update manual release and push to main to allow for nvmrc usage

- packages/lwc-language-server/src/javascript/compiler.ts
- Removes console.log() that was accidentally committed in #544 
@W-12770814@
> fix: remove console.log

- CONTRIBUTING.md
- packages/lightning-lsp-common/src/context.ts
- yarn.lock
The core config file containing environment variables is now build/dev.properties. Use that file instead of config.blt. Additionally handle any errors in parsing and reading by logging to console and not attempting to write to the file.
Also updates documentation for outdated `develop` branch references.
@W-13007946@. Fixes #497. Closes #558.
> fix: update core config file and handle read errors

- README.md
- packages/lwc-language-server/scripts/convert.js
- packages/lwc-language-server/src/__tests__/lwc-data-provider.test.ts
- packages/lwc-language-server/src/resources/standard-lwc.json
Adds support (for autocomplete as well) to the following new LWC directives that were released with 242:
- lwc:if
- lwc:elseif
- lwc:else
@W-12051474@
- Autocomplete
- On hover info
> feat: add new lwc directives as autocomplete options in 242/258

- packages/lightning-lsp-common/src/resources/sfdx/typings/lds.d.ts
1. Adds `ids` to `getDatasets`
2. Adds `validateWaveTemplate`
These are for changes made the adapters in 58.0.
@W-13089840@
cc:  @mblumreich
> feat(common): updates to analyticsWaveApi typings

- packages/lwc-language-server/src/javascript/__tests__/compiler.test.ts
- packages/lwc-language-server/src/javascript/type-mapping.ts
In cases where the main class of a JavaScript file could not be identified, an error was thrown during analysis of the associated metadata. This would cause the language server to crash in VSCode. 👎 
This PR fixes the issue, providing metadata is there is an exported class or if only a single class is defined in the `.js` file. If multiple classes are defined and none of them are default exports, the language server will now return no data. No code hints will be provided, but the language server will not crash.
Fixes forcedotcom/salesforcedx-vscode#4994.
> fix: language server would crash if main class could not be identified

- packages/aura-language-server/bin/aura-language-server.js
- packages/aura-language-server/package.json
- packages/lwc-language-server/bin/lwc-language-server.js
- packages/lwc-language-server/package.json
This PR creates executable files and defines the bin property in package.json for both lwc language server and aura language server.
#581 
This allows the language servers to be run using a terminal command, which in return allows editors like neovim to integrate with language servers using `stdio`. [Neovim LSP DOC](https://neovim.io/doc/user/lsp.html#vim.lsp.start())
> Make lwc & aura language server available to be run from an executable file

- packages/lwc-language-server/src/javascript/__tests__/fixtures/nogetter.js
- packages/lwc-language-server/src/javascript/__tests__/type-mapping.test.ts
- packages/lwc-language-server/src/javascript/type-mapping.ts
Update the javascript type mapping to handle the case where a class has a property with only a setter.
@W-14391061@
https://github.com/forcedotcom/salesforcedx-vscode/issues/5069
> fix: update metadata mapping to handle no getter

- packages/lightning-lsp-common/src/__tests__/context.test.ts
- packages/lightning-lsp-common/src/context.ts
Since we started to support TypeScript for LWC on core, we added `tsconfig.json` files on core's UI modules directory, e.g., `ui-force-components/tsconfig.json`. This `tsconfig.json` would conflict with `jsconfig.json` file that is automatically generated. This PR disable the generation of `jsconfig.json` file on core if there is an existing `jsconfig.json` file on core.
@W-14590716@
https://github.com/forcedotcom/lightning-language-server/assets/113132642/b6c4cd88-08fa-41ae-97ec-8577709598b8
https://github.com/forcedotcom/lightning-language-server/assets/113132642/89fae34f-c8db-42a4-a1f1-864d75bf040f
> fix: do not write jsconfig.json on core when there is tsconfig.json

- .github/workflows/unitTests.yml
This PR temporarily fixes #592 for GHA tests.
Pinning the version of Node in the CI to node v18 for now to unblock other PRs.
> test: pin ci to node v18

- packages/lightning-lsp-common/src/__tests__/context.test.ts
- packages/lightning-lsp-common/src/context.ts
This PR adds `tsconfig.json` and `.ts` file extensions to the `.forceignore` file.
@W-15577958@
> feat: add `tsconfig` and `.ts` file extensions to `.forceignore`

- packages/aura-language-server/src/resources/lwc-standard.json
- packages/lwc-language-server/src/resources/lwc-standard.json
- packages/lwc-language-server/src/resources/standard-lwc.json
Supports lwc-record-picker [W-14457297](https://gus.lightning.force.com/a07EE00001e7vodYAA)
@W-14457297@
> feat: support lwc-record-picker

- packages/lightning-lsp-common/src/__tests__/context.test.ts
- packages/lightning-lsp-common/src/context.ts
- packages/lightning-lsp-common/src/resources/sfdx/tsconfig-sfdx.base.json
- packages/lightning-lsp-common/src/resources/sfdx/tsconfig-sfdx.json
- packages/lightning-lsp-common/src/utils.ts
- packages/lwc-language-server/src/__tests__/component-indexer.test.ts
- packages/lwc-language-server/src/__tests__/lwc-server.test.ts
- packages/lwc-language-server/src/component-indexer.ts
- packages/lwc-language-server/src/constants.ts
- packages/lwc-language-server/src/lwc-server.ts
- test-workspaces/sfdx-workspace/force-app/main/default/lwc/typescript/typescript.html
- test-workspaces/sfdx-workspace/force-app/main/default/lwc/typescript/typescript.js-meta.xml
- test-workspaces/sfdx-workspace/force-app/main/default/lwc/typescript/typescript.ts
This PR adds the ability for the language server to update the `paths` mapping in `tsconfig.sfdx.json`.
The purpose for doing this is to allow TypeScript to determine where to locate an LWC component.
For example:
```js
import Foo from 'c/bar';
...
```
TypeScript doesn't know how to resolve`c/bar` and requires it to be mapped in the `tsconfig.json`, ex:
```js
{
"compilerOptions": {
"paths": {
"c/*": ["/user/some/where/*/bar"]
}
}
}
```
The path mapping is updating in 2 scenarios:
1. When the language server first starts.
2. When there is a file change to a js or ts LWC component.
What issues does this PR fix or reference?
@W-15572824@
> feat: automatically update `tsconfig.sfdx.json`'s paths 

- packages/lightning-lsp-common/src/__tests__/context.test.ts
- packages/lightning-lsp-common/src/resources/sfdx/jsconfig-sfdx.json
- Moves `paths` property to the right place in jsconfig.json, inside `compilerOptions` 
@W-15374337@
> fix: valid js config file

- packages/lightning-lsp-common/src/__tests__/context.test.ts
- packages/lightning-lsp-common/src/context.ts
- packages/lightning-lsp-common/src/resources/sfdx/tsconfig-sfdx.base.json
This PR updates the language server to only add TypeScript-related files to the `.forceignore` if the project has TypeScript support enabled. It also sets an additional option in the base tsconfig that is required for projects to correctly resolve modules.
Fixes https://github.com/forcedotcom/salesforcedx-vscode/issues/5802
@W-16625817@
> fix(forceignore): only add tsconfig + ts to forceignore for TS projects @W-16625817@ 

- packages/lwc-language-server/package.json
- yarn.lock
Should resolve https://github.com/forcedotcom/salesforcedx-vscode/security/dependabot/64
@W-19665164@
> fix: bump dep versions: W-19665164

- packages/aura-language-server/package.json
- packages/aura-language-server/src/__tests__/package-dependencies.test.ts
- packages/aura-language-server/src/tern/bin/tern
- packages/aura-language-server/src/tern/package.json
- packages/lightning-lsp-common/package.json
- packages/lightning-lsp-common/src/__tests__/package-dependencies.test.ts
- packages/lightning-lsp-common/src/base-context.ts
- packages/lwc-language-server/package.json
- packages/lwc-language-server/src/__tests__/package-dependencies.test.ts
- yarn.lock
should fix the sync issue and failing e2e tests for js go to definition.
@W-19605327@
> fix: sync issue and e2e W-19605327
